export type Trainee = {
    id: string;
    name: string;
    phone_number: string;
    dob: string;
    gender: string;
    profession?: string;
    height: number;
    weight: number;
    bmi?: number;
    start_date?: string;
    membership_type?: string;
    emergency_contact?: string;
    medical_history?: string;
    goals?: string;
    notes?: string;
    active_status: boolean;
    social_handle?: string;
    image_url?: string;
    active_supplements?: string;
};
